export const faultCategories = [
  // 🔴 Active Faults - Red
  { category: 'Active Fault', type: 'Solid', color: 'red' },
  { category: 'Active Fault', type: 'Hachured (N)', color: 'red' },
  { category: 'Active Fault', type: 'Hachured (E)', color: 'red' },
  { category: 'Active Fault', type: 'Hachured (S)', color: 'red' },
  { category: 'Active Fault', type: 'Hachured (W)', color: 'red' },
  { category: 'Active Fault', type: 'Hachured (E)', color: 'orange' }, // Exception
  { category: 'Active Fault', type: 'Solid (Sawteeth - E)', color: 'red' },
  { category: 'Active Fault', type: 'Solid (Sawteeth - S)', color: 'red' },
  { category: 'Active Fault', type: 'Solid (Sawteeth - W)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Hachured - N)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Hachured - W)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Hachured - S)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Hachured - E)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Sawteeth - N)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Sawteeth - E)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Sawteeth - W)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Sawteeth - S)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Arrows - E)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Arrows - W)', color: 'red' },
  { category: 'Active Fault', type: 'Dashed (Arrows - S)', color: 'red' },
  { category: 'Active Fault', type: 'Dotted', color: 'red' },

  // ⚫ Potentially Active Faults - Black
  { category: 'Potentially Active Fault', type: 'Solid', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Solid (Sawteeth - W)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Hachured (N)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Hachured (E)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Hachured (S)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Hachured (W)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Hachured - N)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Hachured - E)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Hachured - S)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Hachured - W)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Sawteeth - N)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Sawteeth - W)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Arrows - E)', color: 'black' },
  { category: 'Potentially Active Fault', type: 'Dashed (Arrows - W)', color: 'black' },
];
